-- creating sequences, tables and views. 

--------------------------------------------------------
--  DDL for Sequence ERROR_LINES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ERROR_LOG"."ERROR_LINES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 197 CACHE 20 NOORDER  NOCYCLE  NOKEEP  GLOBAL ;

--------------------------------------------------------
--  DDL for Sequence ERRORS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ERROR_LOG"."ERRORS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 109 CACHE 20 NOORDER  NOCYCLE  NOKEEP  GLOBAL ;

--------------------------------------------------------
--  DDL for Sequence LOG_STACK_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ERROR_LOG"."LOG_STACK_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  GLOBAL ;


--------------------------------------------------------
--  DDL for Table APP_LOG
--------------------------------------------------------

  CREATE TABLE "ERROR_LOG"."APP_LOG" 
   (	"ID" NUMBER, 
	"UNIT" VARCHAR2(65 CHAR), 
	"LINE" NUMBER, 
	"USERNAME" VARCHAR2(128 CHAR), 
	"STIME" TIMESTAMP (6) DEFAULT current_timestamp, 
	"ETIME" TIMESTAMP (6), 
	"PARMS" CLOB, 
	"RESULTS" CLOB
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE &utility_data_tablespace
 LOB ("PARMS") STORE AS SECUREFILE (
  TABLESPACE &utility_lob_tablespace ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE( INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("RESULTS") STORE AS SECUREFILE (
  TABLESPACE &utility_lob_tablespace ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE( INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Index app_log_uidx1
--------------------------------------------------------

  CREATE UNIQUE INDEX "ERROR_LOG"."app_log_uidx1" ON "ERROR_LOG"."APP_LOG" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  tablespace &utility_index_tablespace ;
--------------------------------------------------------
--  Constraints for Table APP_LOG
--------------------------------------------------------

  ALTER TABLE "ERROR_LOG"."APP_LOG" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  tablespace &utility_index_tablespaceindex_tablespace ENABLE;

--------------------------------------------------------
--  DDL for Table ERRORS
--------------------------------------------------------

  CREATE TABLE "ERROR_LOG"."ERRORS" 
   (	"ID" NUMBER, 
	"USERNAME" VARCHAR2(128 BYTE), 
	"IP_ADDRESS" VARCHAR2(15 BYTE), 
	"TIMESTAMP#" TIMESTAMP (6) WITH TIME ZONE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE &utility_data_tablespace ;

   COMMENT ON COLUMN "ERROR_LOG"."ERRORS"."ID" IS 'Primary key for the errors table.';
   COMMENT ON COLUMN "ERROR_LOG"."ERRORS"."USERNAME" IS 'The user that executed the code.';
   COMMENT ON COLUMN "ERROR_LOG"."ERRORS"."IP_ADDRESS" IS 'the ip address that the code was executed from.';
   COMMENT ON COLUMN "ERROR_LOG"."ERRORS"."TIMESTAMP#" IS 'the timestamp when the code was executed.';
--------------------------------------------------------
--  DDL for Index ERRORS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ERROR_LOG"."ERRORS_PK" ON "ERROR_LOG"."ERRORS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE &utility_index_tablespace ;
--------------------------------------------------------
--  Constraints for Table ERRORS
--------------------------------------------------------

  ALTER TABLE "ERROR_LOG"."ERRORS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ERROR_LOG"."ERRORS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "ERROR_LOG"."ERRORS" ADD CONSTRAINT "ERRORS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE &utility_index_tablespace  ENABLE;
  
--------------------------------------------------------
--  DDL for Table ERROR_LINES
--------------------------------------------------------

  CREATE TABLE "ERROR_LOG"."ERROR_LINES" 
   (	"ID" NUMBER, 
	"ERRORS_ID" NUMBER, 
	"DYNAMIC_DEPT" NUMBER, 
	"OWNER" VARCHAR2(128 BYTE), 
	"SUBPRG_NAME" VARCHAR2(128 BYTE), 
	"ERROR_MSG" VARCHAR2(256 BYTE), 
	"ERROR_NUMBER" NUMBER, 
	"PLSQL_LINE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE &utility_data_tablespace ;

   COMMENT ON COLUMN "ERROR_LOG"."ERROR_LINES"."OWNER" IS 'the owner of the pl/sql unit that was called.';
   COMMENT ON COLUMN "ERROR_LOG"."ERROR_LINES"."SUBPRG_NAME" IS 'the function,procedure that was called in a package. we are leaving this nullable for now. there is the possibility that a procedure,function,trigger can be called and will not be part of a package.';
--------------------------------------------------------
--  DDL for Index ERROR_LINES__IDX
--------------------------------------------------------

  CREATE INDEX "ERROR_LOG"."ERROR_LINES__IDX" ON "ERROR_LOG"."ERROR_LINES" ("ERRORS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE &utility_index_tablespace ;
--------------------------------------------------------
--  DDL for Index ERROR_LINES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ERROR_LOG"."ERROR_LINES_PK" ON "ERROR_LOG"."ERROR_LINES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE &utility_index_tablespace ;
--------------------------------------------------------
--  Constraints for Table ERROR_LINES
--------------------------------------------------------

  ALTER TABLE "ERROR_LOG"."ERROR_LINES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ERROR_LOG"."ERROR_LINES" MODIFY ("ERRORS_ID" NOT NULL ENABLE);
  ALTER TABLE "ERROR_LOG"."ERROR_LINES" MODIFY ("DYNAMIC_DEPT" NOT NULL ENABLE);
  ALTER TABLE "ERROR_LOG"."ERROR_LINES" ADD CONSTRAINT "ERROR_LINES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE &utility_index_tablespace ENABLE;